version: '3'
services:
  certbot:
    build: ./certbot/
    volumes:
      - ./certbot/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/run.sh:/root/run.sh:ro
      - ./result:/root/result:rw
    ports:
      - "80:80"
    working_dir: /root
    stdin_open: true
    command: sleep 100000

